# Configuration for what parts of the Estimates Program to run. Since this file may be
# modified from the default settings, you can always restore to default using the copy
# stored in README.md. For brevity, detailed comments have been removed from this file

# The `run` section contains configuration for running every module of the Estimates
# Program for a specified set of years
[run]
enabled = true
mgra = "mgra15"
start_year = 2020
end_year = 2020
version = "1.1.1-dev"
comments = "Example comment"

# The `debug` section contains configuration for running a single module for a single
# year based on the input data of an existing complete Estimates run. The input module
# string can be any of "startup", "housing_and_households", "population",
# "population_by_ase", "household_characteristics", "employment", or "staging"
[debug]
enabled = false
run_id = 82 # The run_id for the released v24 Estimates
year = 2020
module = ""
