/*
Get census tract controls for households by household size. Census tracts without a
distribution default to using the regional

Controls are generated by the 5-year ACS Detailed Tables
    B11016 - Household Type by Household Size

Two input parameters are used
    run_id - the run identifier is used to get the list of census tracts in tandem with
        the year parameter that determines their vintage
    year - the year parameter is used to identify the 5-year ACS Detailed Tables release
        to use (ex. 2023 maps to 2019-2023) and the census tract geography vintage
        (2010-2019 uses 2010, 2020-2029 uses 2020)
*/

SET NOCOUNT ON;

-- Send error message if no data exists ------------------------------------------------
DECLARE @msg nvarchar(45) = 'ACS 5-Year Table does not exist';
IF NOT EXISTS (
    SELECT TOP (1) *
    FROM [acs].[detailed].[tables]
    WHERE
        [name] = 'B11016'
        AND [year] = @year
        AND [product] = '5Y'
)
SELECT @msg AS [msg]
ELSE
BEGIN

    -- Initialize parameters and return table ------------------------------------------
    DECLARE @run_id integer = :run_id;
    DECLARE @year integer = :year;

    -- Build the expected return table Tract x Structure Type
    DROP TABLE IF EXISTS [#tt_shell];
    SELECT
        [tract],
        [household_size]
    INTO [#tt_shell]
    FROM (
        SELECT DISTINCT
            CASE WHEN @year BETWEEN 2010 AND 2019 THEN [2010_census_tract]
                 WHEN @year BETWEEN 2020 AND 2029 THEN [2020_census_tract]
                 ELSE NULL END AS [tract]
        FROM [inputs].[mgra]
        WHERE [run_id] = @run_id
    ) AS [tracts]
    CROSS JOIN (
        SELECT [household_size] FROM (
            VALUES
                (1),
                (2),
                (3),
                (4),
                (5),
                (6),
                (7)
        ) AS [tt] ([household_size])
    ) AS [household_size];


    -- Prepare intermediary results from ACS datasets ----------------------------------
    -- 5-year ACS Detailed Table B11016 - Household Type by Household Size
    DROP TABLE IF EXISTS [#hh_by_hhs];
    SELECT
        [tract],
        [household_size],
        SUM([value]) AS [hh]
    INTO [#hh_by_hhs]
    FROM (
        SELECT
            [tract],
            -- The '%' wildcard matches both 'Family households' and 'Nonfamily
            -- households'
            CASE
                WHEN [label] LIKE 'Estimate%1-person household' THEN 1
                WHEN [label] LIKE 'Estimate%2-person household' THEN 2
                WHEN [label] LIKE 'Estimate%3-person household' THEN 3
                WHEN [label] LIKE 'Estimate%4-person household' THEN 4
                WHEN [label] LIKE 'Estimate%5-person household' THEN 5
                WHEN [label] LIKE 'Estimate%6-person household' THEN 6
                WHEN [label] LIKE 'Estimate%7-or-more person household' THEN 7
                ELSE NULL  -- NULL values for Margin of Error fields removed in subsequent WHERE clause
            END AS [household_size],
            [value]
        FROM [acs].[detailed].[values]
        LEFT JOIN [acs].[detailed].[geography]
            ON [values].[geography_id] = [geography].[geography_id]
        LEFT JOIN [acs].[detailed].[variables]
            ON [values].[variable] = [variables].[variable]
            AND [values].[table_id] = [variables].[table_id]
        LEFT JOIN [acs].[detailed].[tables]
            ON [values].[table_id] = [tables].[table_id]
        WHERE
            [tables].[name] = 'B11016'
            AND [tables].[year] = @year
            AND [tables].[product] = '5Y'
    ) AS [b11016]
    WHERE [household_size] IS NOT NULL
    GROUP BY [tract], [household_size]

    -- Create hh size distribution -----------------------------------------------------
    -- Calculate regional hh size distribution
    DECLARE @total_hh INTEGER = (SELECT SUM([hh]) FROM [#hh_by_hhs]);
    WITH [region_hhs_distribution] AS (
            SELECT
                [household_size],
                1.0 * SUM([hh]) / @total_hh AS [hh_dist]
            FROM [#hh_by_hhs]
            GROUP BY [household_size]
        ),
        -- Calculate census tract hh by hhs distribution
        [tract_distribution] AS (
            SELECT
                [#hh_by_hhs].[tract],
                [household_size],
                CASE
                    WHEN [tract_total_hh].[hh] = 0 THEN NULL
                    ELSE [#hh_by_hhs].[hh] / [tract_total_hh].[hh]
                END AS [hh_dist]
            FROM [#hh_by_hhs]
            LEFT JOIN (
                    SELECT
                        [tract],
                        SUM([hh]) AS [hh]
                    FROM [#hh_by_hhs]
                    GROUP BY [tract]
                ) AS [tract_total_hh]
                ON [#hh_by_hhs].[tract] = [tract_total_hh].[tract]
        )
    SELECT
        @run_id AS [run_id],
        @year AS [year],
        [#tt_shell].[tract],
        [#tt_shell].[household_size],
        ISNULL([tract_distribution].[hh_dist], [region_hhs_distribution].[hh_dist]) AS [value]
    FROM [#tt_shell]
    LEFT JOIN [region_hhs_distribution]
        ON [#tt_shell].[household_size] = [region_hhs_distribution].[household_size]
    LEFT JOIN [tract_distribution]
        ON [#tt_shell].[tract] = [tract_distribution].[tract]
        AND [#tt_shell].[household_size] = [tract_distribution].[household_size]

END