/*
Get census tract controls for households by number of workers. Census tracts without a
distribution default to using the regional distribution.

Controls are generated by the 5-year ACS Detailed Tables
    B08202 - Household Size by Number of Workers in Household

Two input parameters are used
    run_id - the run identifier is used to get the list of census tracts in tandem with
        the year parameter that determines their vintage
    year - the year parameter is used to identify the 5-year ACS Detailed Tables release
        to use (ex. 2023 maps to 2019-2023) and the census tract geography vintage
        (2010-2019 uses 2010, 2020-2029 uses 2020)
*/

SET NOCOUNT ON;

-- Initialize parameters ---------------------------------------------------------------
DECLARE @run_id integer = :run_id;
DECLARE @year integer = :year;
DECLARE @series INTEGER = (SELECT [series] FROM [metadata].[run] WHERE [run_id] = @run_id);

-- Send error message if no data exists ------------------------------------------------
DECLARE @msg nvarchar(45) = 'ACS 5-Year Table does not exist';
IF NOT EXISTS (
    SELECT TOP (1) *
    FROM [acs].[detailed].[tables]
    WHERE
        [name] = 'B08202'
        AND [year] = @year
        AND [product] = '5Y'
)
SELECT @msg AS [msg]
ELSE
BEGIN

    -- Build the expected return table Tract x Workers
    DROP TABLE IF EXISTS [#tt_shell];
    SELECT
        [tract],
        [workers]
    INTO [#tt_shell]
    FROM (
        SELECT DISTINCT [tract]
        FROM [demographic_warehouse].[dim].[mgra]
        INNER JOIN [demographic_warehouse].[dim].[mgra_xref]
            ON [mgra].[mgra_id] = [mgra_xref].[mgra_id]
            AND [mgra_xref].[xref_year] = @year
        WHERE [mgra].[series] = @series
    ) AS [tracts]
    CROSS JOIN (
        SELECT [workers] FROM (
            VALUES
                (0),
                (1),
                (2),
                (3)
        ) AS [tt] ([workers])
    ) AS [workers];


    -- Prepare intermediary results from ACS datasets ----------------------------------
    -- 5-year ACS Detailed Table B08202 - Household Size by Number of Workers in Household
    DROP TABLE IF EXISTS [#hh_by_workers];
    SELECT
        [tract],
        [workers],
        SUM([value]) AS [hh]
    INTO [#hh_by_workers]
    FROM (
        SELECT
            [tract],
            -- The '%' wildcard matches both 'Family households' and 'Nonfamily
            -- households'
            CASE
                WHEN REPLACE([label], ':', '') = 'Estimate!!Total!!No workers' THEN 0
                WHEN REPLACE([label], ':', '') = 'Estimate!!Total!!1 worker' THEN 1
                WHEN REPLACE([label], ':', '') = 'Estimate!!Total!!2 workers' THEN 2
                WHEN REPLACE([label], ':', '') = 'Estimate!!Total!!3 or more workers' THEN 3
                ELSE NULL  -- NULL values for Margin of Error fields removed in subsequent WHERE clause
            END AS [workers],
            [value]
        FROM [acs].[detailed].[values]
        LEFT JOIN [acs].[detailed].[geography]
            ON [values].[geography_id] = [geography].[geography_id]
        LEFT JOIN [acs].[detailed].[variables]
            ON [values].[variable] = [variables].[variable]
            AND [values].[table_id] = [variables].[table_id]
        LEFT JOIN [acs].[detailed].[tables]
            ON [values].[table_id] = [tables].[table_id]
        WHERE
            [tables].[name] = 'B08202'
            AND [tables].[year] = @year
            AND [tables].[product] = '5Y'
    ) AS [b08202]
    WHERE [workers] IS NOT NULL
    GROUP BY [tract], [workers]

    -- Create hh workers distribution --------------------------------------------------
    -- Calculate regional hh by workers distribution
    DECLARE @total_hh INTEGER = (SELECT SUM([hh]) FROM [#hh_by_workers]);
    WITH [region_workers_distribution] AS (
            SELECT
                [workers],
                1.0 * SUM([hh]) / @total_hh AS [hh_dist]
            FROM [#hh_by_workers]
            GROUP BY [workers]
        ),
        -- Calculate census tract hh by workers distribution
        [tract_distribution] AS (
            SELECT
                [#hh_by_workers].[tract],
                [workers],
                CASE
                    WHEN [tract_total_hh].[hh] = 0 THEN NULL
                    ELSE [#hh_by_workers].[hh] / [tract_total_hh].[hh]
                END AS [hh_dist]
            FROM [#hh_by_workers]
            LEFT JOIN (
                    SELECT
                        [tract],
                        SUM([hh]) AS [hh]
                    FROM [#hh_by_workers]
                    GROUP BY [tract]
                ) AS [tract_total_hh]
                ON [#hh_by_workers].[tract] = [tract_total_hh].[tract]
        )
    SELECT
        @run_id AS [run_id],
        @year AS [year],
        [#tt_shell].[tract],
        [#tt_shell].[workers],
        ISNULL([tract_distribution].[hh_dist], [region_workers_distribution].[hh_dist]) AS [value]
    FROM [#tt_shell]
    LEFT JOIN [region_workers_distribution]
        ON [#tt_shell].[workers] = [region_workers_distribution].[workers]
    LEFT JOIN [tract_distribution]
        ON [#tt_shell].[tract] = [tract_distribution].[tract]
        AND [#tt_shell].[workers] = [tract_distribution].[workers]
    ORDER BY 
        [#tt_shell].[tract],
        [#tt_shell].[workers];
END