# Container for the Household Characteristics module. See the Estimates-Program wiki
# page for more details:
# https://github.com/SANDAG/Estimates-Program/wiki/Household-Characteristics

import numpy as np
import pandas as pd
import sqlalchemy as sql

import python.utils as utils
import python.tests as tests

generator = np.random.default_rng(utils.RANDOM_SEED)


def run_hh_characteristics(year: int, debug: bool) -> None:
    """Orchestrator function to calculate and insert household characteristics.

    The household characteristics created are:
        1. Households by household income category
        2. Households by number of people in each household (size)
        3. Households by number of workers in each household (workers)

    All characteristics are generated by applying ACS data to MGRA level households,
    which are created by the Housing and Households module. Functionality is segmented
    into functions for code encapsulation.

    The following functions are used for households by income category:
        _get_hh_income_inputs - Get MGRA households and ACS tract distributions for
            household income categories
        _validate_hh_income_inputs - Validate the household income category input data
        _create_hh_income - Calculate the household income, control to MGRA households
        _validate_hh_income_outputs - Validate the household income output data
        _insert_hh_income - Insert household income and tract level income
            distributions to the production database

    The following functions are used for households by size:
        _get_hh_size_inputs - Get MGRA households, MGRA household population, and ACS
            tract distributions for household size
        _validate_hh_size_inputs - Validate the household size input data
        _create_hh_size - Calculate the household size, control to MGRA households and
            MGRA household population
        _validate_hh_size_outputs - Validate the household size output data
        _insert_hh_size - Insert household size and tract level size distributions to
            the production database

    The following functions are used for households by workers:
        _get_hh_workers_inputs - Get MGRA households, MGRA population aged 18+, MGRA
            households by size, and ACS tract distributions for households workers
        _validate_hh_workers_inputs - Validate the household workers input data
        _create_hh_workers - Calculate the household workers, control to MGRA
            households, MGRA population aged 18+, and MGRA households by size
        _validate_hh_workers_outputs - Validate the household workers output data
        _insert_hh_workers - Insert household workers and tract level workers
            distributions to the production database

    Args:
        year (int): estimates year
    """
    # Start with household income
    hh_income_inputs = _get_hh_income_inputs(year)
    _validate_hh_income_inputs(year, hh_income_inputs)

    hh_income_outputs = _create_hh_income(hh_income_inputs)
    _validate_hh_income_outputs(hh_income_outputs)

    _insert_hh_income(hh_income_inputs, hh_income_outputs, debug)

    # Then do households by size
    hh_size_inputs = _get_hh_size_inputs(year)
    _validate_hh_size_inputs(year, hh_size_inputs)

    hh_size_outputs = _create_hh_size(hh_size_inputs)
    _validate_hh_size_outputs(hh_size_outputs)

    _insert_hh_size(hh_size_inputs, hh_size_outputs, debug)

    # And finally do households by workers
    hh_workers_inputs = _get_hh_workers_inputs(year)
    _validate_hh_workers_inputs(year, hh_workers_inputs)

    hh_workers_outputs = _create_hh_workers(hh_workers_inputs)
    _validate_hh_workers_outputs(hh_workers_outputs)

    _insert_hh_workers(hh_workers_inputs, hh_workers_outputs, debug)


def _get_hh_income_inputs(year: int) -> dict[str, pd.DataFrame]:
    """Get households and various tract level datas"""
    with utils.ESTIMATES_ENGINE.connect() as con:
        # Store results here
        hh_income_inputs = {}

        # Get MGRA level households. Note we re-use the SQL script from the 'Population
        # by Type' module
        with open(utils.SQL_FOLDER / "pop_type" / "get_mgra_hh.sql") as file:
            hh_income_inputs["hh"] = pd.read_sql_query(
                sql=sql.text(file.read()),
                con=con,
                params={
                    "run_id": utils.RUN_ID,
                    "year": year,
                },  # type: ignore
            ).drop(columns=["jurisdiction"])

        # Tract level household income distributions
        with open(
            utils.SQL_FOLDER / "hh_characteristics" / "get_tract_controls_hh_income.sql"
        ) as file:
            hh_income_inputs["hh_income_tract_controls"] = (
                utils.read_sql_query_fallback(
                    sql=sql.text(file.read()),  # type: ignore
                    con=con,  # type: ignore
                    params={"run_id": utils.RUN_ID, "year": year},
                )
            )

    return hh_income_inputs


def _get_hh_size_inputs(year: int) -> dict[str, pd.DataFrame]:
    """Get households and various tract level datas."""
    with utils.ESTIMATES_ENGINE.connect() as con:
        # Store results here
        hh_size_inputs = {}

        # Get MGRA level households. Note we re-use the SQL script from the 'Population
        # by Type' module
        with open(utils.SQL_FOLDER / "pop_type" / "get_mgra_hh.sql") as file:
            hh_size_inputs["hh"] = pd.read_sql_query(
                sql=sql.text(file.read()),
                con=con,
                params={
                    "run_id": utils.RUN_ID,
                    "year": year,
                },  # type: ignore
            ).drop(columns=["jurisdiction"])

        # Tract level households by household size distributions
        with open(
            utils.SQL_FOLDER
            / "hh_characteristics"
            / "get_tract_controls_hh_by_size.sql"
        ) as file:
            hh_size_inputs["hhs_tract_controls"] = utils.read_sql_query_fallback(
                sql=sql.text(file.read()),  # type: ignore
                con=con,  # type: ignore
                params={"run_id": utils.RUN_ID, "year": year},
            )

        # MGRA level household size controls
        with open(
            utils.SQL_FOLDER / "hh_characteristics" / "get_mgra_controls_hh_by_size.sql"
        ) as file:
            hh_size_inputs["hhs_mgra_controls"] = pd.read_sql_query(
                sql=sql.text(file.read()),
                con=con,
                params={"run_id": utils.RUN_ID, "year": year},  # type: ignore
            )

    return hh_size_inputs


def _get_hh_workers_inputs(year: int) -> dict[str, pd.DataFrame]:
    """Get MGRA and tract level controls for households by workers."""
    with utils.ESTIMATES_ENGINE.connect() as con:
        # Store results here
        hh_workers_inputs = {}

        # Get MGRA level households. Note we re-use the SQL script from the 'Population
        # by Type' module
        with open(utils.SQL_FOLDER / "pop_type" / "get_mgra_hh.sql") as file:
            hh_workers_inputs["hh"] = pd.read_sql_query(
                sql=sql.text(file.read()),
                con=con,
                params={
                    "run_id": utils.RUN_ID,
                    "year": year,
                },  # type: ignore
            ).drop(columns=["jurisdiction"])

        # Get MGRA level population aged 18+
        with open(
            utils.SQL_FOLDER
            / "hh_characteristics"
            / "get_mgra_controls_hh_by_workers_18plus.sql"
        ) as file:
            hh_workers_inputs["mgra_18plus"] = pd.read_sql_query(
                sql=sql.text(file.read()),
                con=con,
                params={"run_id": utils.RUN_ID, "year": year},  # type: ignore
            )

        # Get MGRA level households by size
        with open(
            utils.SQL_FOLDER
            / "hh_characteristics"
            / "get_mgra_controls_hh_by_workers_hhs.sql"
        ) as file:
            hh_workers_inputs["mgra_hhs"] = pd.read_sql_query(
                sql=sql.text(file.read()),
                con=con,
                params={"run_id": utils.RUN_ID, "year": year},  # type: ignore
            )

        # Get tract level households by workers distributions
        with open(
            utils.SQL_FOLDER
            / "hh_characteristics"
            / "get_tract_controls_hh_by_workers.sql"
        ) as file:
            hh_workers_inputs["tract_workers"] = utils.read_sql_query_fallback(
                sql=sql.text(file.read()),
                con=con,
                params={"run_id": utils.RUN_ID, "year": year},  # type: ignore
            )

    return hh_workers_inputs


def _validate_hh_income_inputs(
    year: int, hh_char_inputs: dict[str, pd.DataFrame]
) -> None:
    """Validate the household characteristics input data"""
    tests.validate_data(
        "MGRA households",
        hh_char_inputs["hh"],
        row_count={"key_columns": {"mgra"}},
        negative={},
        null={},
    )
    tests.validate_data(
        "Tract household income distribution",
        hh_char_inputs["hh_income_tract_controls"],
        row_count={"key_columns": {"tract", "income_category"}, "year": year},
        negative={},
        null={},
    )


def _validate_hh_size_inputs(
    year: int, hh_size_inputs: dict[str, pd.DataFrame]
) -> None:
    """Validate the household characteristics input data"""
    tests.validate_data(
        "MGRA households",
        hh_size_inputs["hh"],
        row_count={"key_columns": {"mgra"}},
        negative={},
        null={},
    )
    tests.validate_data(
        "Tract households by household size distribution",
        hh_size_inputs["hhs_tract_controls"],
        row_count={"key_columns": {"tract", "household_size"}, "year": year},
        negative={},
        null={},
    )
    tests.validate_data(
        "MGRA households by household size controls",
        hh_size_inputs["hhs_mgra_controls"],
        row_count={"key_columns": {"mgra"}},
        negative={},
        null={},
    )


def _validate_hh_workers_inputs(
    year: int, hh_workers_inputs: dict[str, pd.DataFrame]
) -> None:
    """Validate the household characteristics input data"""
    tests.validate_data(
        "MGRA households",
        hh_workers_inputs["hh"],
        row_count={"key_columns": {"mgra"}},
        negative={},
        null={},
    )
    tests.validate_data(
        "MGRA persons aged 18+ controls",
        hh_workers_inputs["mgra_18plus"],
        row_count={"key_columns": {"mgra"}},
        negative={},
        null={},
    )
    tests.validate_data(
        "MGRA households by household size controls",
        hh_workers_inputs["mgra_hhs"],
        row_count={"key_columns": {"mgra"}},
        negative={},
        null={},
    )
    tests.validate_data(
        "Tract households by household workers distribution",
        hh_workers_inputs["tract_workers"],
        row_count={"key_columns": {"tract", "household_workers"}, "year": year},
        negative={},
        null={},
    )


def _create_hh_income(
    hh_income_inputs: dict[str, pd.DataFrame],
) -> dict[str, pd.DataFrame]:
    """Code to compute MGRA household income"""
    hh = hh_income_inputs["hh"]
    tract_income_dist = hh_income_inputs["hh_income_tract_controls"]

    # Combine the total households in each MGRA with the distribution of households by
    # income
    hh_income = (
        hh.merge(tract_income_dist, on=["run_id", "year", "tract"], how="left")
        .assign(hh=lambda df: df["hh"] * df["value"])
        .drop(columns=["value"])
        .pivot(
            index=["run_id", "year", "mgra", "tract"],
            columns="income_category",
            values="hh",
        )
        .reset_index(drop=False)
        .sort_values(by="mgra")
        .reset_index(drop=True)
    )

    # To ensure that we pretty much exactly match ACS distributions, we will do two
    # dimensional controlling on the MGRA level data. After splitting the data into
    # separate tracts, row controls will be total households in each MGRA and column
    # controls will be tract level household income
    controlled_groups = []
    for tract, group in hh_income.groupby("tract"):
        seed_data = group[utils.INCOME_CATEGORIES].to_numpy()

        row_controls = (
            group[utils.INCOME_CATEGORIES].sum(axis=1).to_numpy().round(0).astype(int)
        )

        col_controls = utils.integerize_1d(
            group[utils.INCOME_CATEGORIES].sum(axis=0), generator=generator
        )

        controlled_data = utils.integerize_2d(
            data=seed_data,
            row_ctrls=row_controls,
            col_ctrls=col_controls,
            condition="exact",
            suppress_warnings=True,
            generator=generator,
        )

        # Assign the controlled data back to the tract
        group[utils.INCOME_CATEGORIES] = controlled_data
        controlled_groups.append(group)

    # Coerce the controlled data back into the original format. Note that pd.melt()
    # does not include the "tract" column, which functionally drops it
    hh_income = pd.concat(controlled_groups).melt(
        id_vars=["run_id", "year", "mgra"],
        value_vars=utils.INCOME_CATEGORIES,
        var_name="income_category",
        value_name="hh",
    )

    return {"hh_income": hh_income}


def _create_hh_size(
    hh_size_inputs: dict[str, pd.DataFrame],
) -> dict[str, pd.DataFrame]:
    """Code to compute MGRA level households by size

    Similar to how income works, this function takes MGRA households, applies tract
    level rates, then integerizes the data. But additionally, we control to MGRA hhp.
    This is because the distribution of households by household size implies some
    minimum and maximum household population.

    For example, if we had 10 households of size one, 10 households of size two, ...,
    10 households of size 7+, the minimum amount of household population would be 1*10
    + 2*10 + ... + 7*10 = 280. On the flip side, the maximum amount of household
    population, assuming the 7+ category all maxes out at 11 people, would be 1*10
    + 2*10 + ... + 11*10 = 320. Thus, the actual amount of household population in this
    MGRA must be between these 280 and 320. In MGRAs where there are zero 7+ households,
    the household size distribution implies an exact amount of household population
    instead of a range.

    In order to perfectly align the implied household population and the actual
    household population, we have to manually move some households up or down the
    size distribution, which naturally shifts the implied household population up or
    down as well.

    Specifically, if an MGRA needs implied/actual household population adjustment, then
    first a random household size is chosen, weighted by the number of households in
    each size. Then, depending on if we need to increase or decrease the implied
    household population, we choose a second random household size (non-weighted) above
    or below the first household size. The first household size loses one household,
    the second household size gains a household. This shifts the implied household
    population up/down a small amount, which is repeated until the implied/actual
    household population are consistent

    Finally, note that for household size, the 7+ category can technically include sizes
    up to ∞. But for the purposes of balancing implied/actual household population, we
    assume that every household in the 7+ category has 11 people, which is roughly the
    max we see from San Diego PUMS data. See GitHub for more details:
    https://github.com/SANDAG/Estimates-Program/issues/112
    """
    n_people_in_7_plus = 11

    hh = hh_size_inputs["hh"]
    tract_hhs_dist = hh_size_inputs["hhs_tract_controls"]
    mgra_controls = hh_size_inputs["hhs_mgra_controls"]

    # Combine the total households in each MGRA with the distribution of households by
    # size
    hh_size = (
        hh.merge(tract_hhs_dist, on=["run_id", "year", "tract"], how="left")
        .assign(hh=lambda df: df["hh"] * df["value"])
        .drop(columns=["value"])
        .pivot(
            index=["run_id", "year", "mgra", "tract"],
            columns="household_size",
            values="hh",
        )
        .reset_index(drop=False)
        .sort_values(by="mgra")
        .reset_index(drop=True)
    )

    # To ensure that we pretty much exactly match ACS distributions, we will do two-
    # dimensional controlling on the MGRA level data. After splitting the data into
    # separate tracts, row controls will be total households in each MGRA and column
    # controls will be tract level households by size
    controlled_groups = []
    for tract, group in hh_size.groupby("tract"):
        seed_data = group[utils.HOUSEHOLD_SIZES].to_numpy()

        row_controls = (
            group[utils.HOUSEHOLD_SIZES].sum(axis=1).to_numpy().round(0).astype(int)
        )

        col_controls = utils.integerize_1d(
            group[utils.HOUSEHOLD_SIZES].sum(axis=0), generator=generator
        )

        controlled_data = utils.integerize_2d(
            data=seed_data,
            row_ctrls=row_controls,
            col_ctrls=col_controls,
            condition="exact",
            suppress_warnings=True,
            generator=generator,
        )

        # Assign the controlled data back to the tract
        group[utils.HOUSEHOLD_SIZES] = controlled_data
        controlled_groups.append(group)

    # Recombine all the data in preparation for the next controlling step
    hh_size = pd.concat(controlled_groups)

    # For every MGRA, compute the minimum and maximum implied household population, as
    # well as how much the actual household population differs from the implied
    hh_size = (
        hh_size.merge(mgra_controls, on=["run_id", "year", "mgra"], how="left")
        .astype({hhs: int for hhs in utils.HOUSEHOLD_SIZES})
        .assign(
            min_implied_hhp=lambda df: df[1]
            + (2 * df[2])
            + (3 * df[3])
            + (4 * df[4])
            + (5 * df[5])
            + (6 * df[6])
            + (7 * df[7]),
            max_implied_hhp=lambda df: df[1]
            + (2 * df[2])
            + (3 * df[3])
            + (4 * df[4])
            + (5 * df[5])
            + (6 * df[6])
            + (n_people_in_7_plus * df[7]),
            # Then, compute the difference between the actual household population and the
            # implied minimum and maximum. The two following columns are instructions for
            # how to adjust the households by size distribution
            decrease_min=lambda df: np.where(
                df["min_implied_hhp"] > df["hhp_total"],
                df["min_implied_hhp"] - df["hhp_total"],
                0,
            ),
            increase_max=lambda df: np.where(
                df["max_implied_hhp"] < df["hhp_total"],
                df["hhp_total"] - df["max_implied_hhp"],
                0,
            ),
        )
    )

    # The methodology to adjust each individual MGRA. Unfortunately, I don't believe
    # there's any way to do this in parallel manner, given how each MGRA has a different
    # distribution and different change requirements
    def adjust_mgra(mgra_data: pd.Series) -> pd.Series:
        if mgra_data["increase_max"] == 0 and mgra_data["decrease_min"] == 0:
            return mgra_data
        while True:
            # Choose a random household size to decrease, weighted by the number of
            # households in the size. Note the weighting ensures that a household size
            # with non-zero households will always be chosen
            hhs_to_decrease = generator.choice(
                utils.HOUSEHOLD_SIZES,
                p=mgra_data[utils.HOUSEHOLD_SIZES]
                / mgra_data[utils.HOUSEHOLD_SIZES].sum(),
            )

            # Depending on if we want to increase the max implied hhp or decrease the
            # min implied hhp, we look above or below the household size to decrease.
            # But we don't want to go too far above/below, or we could overshoot then
            # have to do the opposite adjustment
            if mgra_data["increase_max"] > 0 and hhs_to_decrease != 7:
                hhs_to_increase = generator.choice(
                    range(
                        hhs_to_decrease + 1,
                        np.min([hhs_to_decrease + mgra_data["increase_max"], 7]) + 1,
                    )
                )
            elif mgra_data["decrease_min"] > 0 and hhs_to_decrease != 1:
                hhs_to_increase = generator.choice(
                    range(
                        np.max([1, hhs_to_decrease - mgra_data["decrease_min"]]),
                        hhs_to_decrease,
                    )
                )
            # The final else covers edge cases, such as when we want to increase the
            # max, but our randomly chosen hhs_to_decrease is already 7+. In such
            # situations, we restart the loop and choose a new hhs_to_decrease
            else:
                continue

            # Execute the change and recompute the remaining change needed
            mgra_data[hhs_to_decrease] -= 1
            mgra_data[hhs_to_increase] += 1
            if mgra_data["increase_max"] > 0:
                mgra_data["increase_max"] -= (hhs_to_increase - hhs_to_decrease) + (
                    n_people_in_7_plus - 7 if hhs_to_increase == 7 else 0
                )
            else:
                mgra_data["decrease_min"] += hhs_to_increase - hhs_to_decrease

            # Check if we are done with this MGRA. Note, the "increase_max" is allowed
            # to overshoot since if the increase size is seven, we actually change the
            # implied hhp by an additional four
            if mgra_data["increase_max"] <= 0 and mgra_data["decrease_min"] == 0:
                return mgra_data

    # Apply the MGRA adjustments
    hh_size = hh_size.apply(adjust_mgra, axis=1)

    # Reshape and return
    return {
        "hh_size": hh_size.drop(
            columns=[
                "tract",
                "hhp_total",
                "min_implied_hhp",
                "max_implied_hhp",
                "decrease_min",
                "increase_max",
            ]
        ).melt(
            id_vars=["run_id", "year", "mgra"],
            var_name="household_size",
            value_name="hh",
        )
    }


def _create_hh_workers(
    hh_workers_inputs: dict[str, pd.DataFrame],
) -> dict[str, pd.DataFrame]:
    """Code to compute MGRA level households by workers

    Similar to how income and size work, this function takes MGRA households, applies
    tract level rates, then integerizes the data. But additionally, we control to the
    MGRA population aged 18+ and MGRA households by size. This is because the
    distribution of households by household workers implies some minimum number of
    workers in the MGRA, which cannot exceed the actual number of workers in the MGRA.
    Because the actual number of workers in the MGRA is not known, we use the
    population aged 18+ as a proxy. Additionally, the distribution of households by
    household workers implies a minimum number of households by size in the 2+ and 3+
    categories, which cannot exceed the actual number of households by size within each
    category in the MGRA.
    """
    hh = hh_workers_inputs["hh"]
    tract_workers_dist = hh_workers_inputs["tract_workers"]
    mgra_18plus = hh_workers_inputs["mgra_18plus"]
    mgra_hhs = hh_workers_inputs["mgra_hhs"]

    # Combine the total households in each MGRA with the distribution of households by
    # number of workers
    hh_workers = (
        hh.merge(tract_workers_dist, on=["run_id", "year", "tract"], how="left")
        .assign(hh=lambda df: df["hh"] * df["value"])
        .drop(columns=["value"])
        .pivot(
            index=["run_id", "year", "mgra", "tract"],
            columns="household_workers",
            values="hh",
        )
        .reset_index(drop=False)
        .sort_values(by="mgra")
        .reset_index(drop=True)
    )

    # To ensure that we pretty much exactly match ACS distributions, we will do two-
    # dimensional controlling on the MGRA level data. After splitting the data into
    # separate tracts, row controls will be total households in each MGRA and column
    # controls will be tract level households by workers
    controlled_groups = []
    for tract, group in hh_workers.groupby("tract"):
        seed_data = group[utils.HOUSEHOLD_WORKERS].to_numpy()

        row_controls = (
            group[utils.HOUSEHOLD_WORKERS].sum(axis=1).to_numpy().round(0).astype(int)
        )

        col_controls = utils.integerize_1d(
            group[utils.HOUSEHOLD_WORKERS].sum(axis=0), generator=generator
        )

        controlled_data = utils.integerize_2d(
            data=seed_data,
            row_ctrls=row_controls,
            col_ctrls=col_controls,
            condition="exact",
            suppress_warnings=True,
            generator=generator,
        )

        # Assign the controlled data back to the tract
        group[utils.HOUSEHOLD_WORKERS] = controlled_data
        controlled_groups.append(group)

    # Recombine all the data in preparation for the next controlling step
    hh_workers = pd.concat(controlled_groups)

    # For every MGRA, compute the minimum implied worker population
    # And difference between implied worker and 18+ population
    hh_workers = (
        hh_workers.merge(mgra_18plus, on=["run_id", "year", "mgra"], how="left")
        .astype({workers: int for workers in utils.HOUSEHOLD_WORKERS})
        .assign(
            min_implied_workers=lambda df: df[1] + (2 * df[2]) + (3 * df[3]),
            # Compute the difference between the 18+ population and the implied minimum
            decrease_min=lambda df: np.where(
                df["min_implied_workers"] > df["persons_18plus"],
                df["min_implied_workers"] - df["persons_18plus"],
                0,
            ),
        )
    )

    # The methodology to adjust each individual MGRA for minimum implied workers
    # TODO: Consider ways to parallelize
    def adjust_mgra_18plus(mgra_data: pd.Series) -> pd.Series:
        if mgra_data["decrease_min"] == 0:
            return mgra_data
        while True:
            # Choose a random household workers category to decrease
            # weighted by the number of households in each category
            workers_to_decrease = generator.choice(
                utils.HOUSEHOLD_WORKERS,
                p=mgra_data[utils.HOUSEHOLD_WORKERS]
                / mgra_data[utils.HOUSEHOLD_WORKERS].sum(),
            )

            # Look below the chosen category for a category to increase
            if mgra_data["decrease_min"] > 0 and workers_to_decrease != 0:
                # Avoid overshooting the decrease
                workers_to_increase = generator.choice(
                    range(
                        np.max([0, workers_to_decrease - mgra_data["decrease_min"]]),
                        workers_to_decrease,
                    )
                )
            # Continue if we need to decrease implied workers but the randomly chosen
            # category was already 0 workers, restart the loop to choose a new category
            else:
                continue

            # Execute the change and recompute the remaining change needed
            mgra_data[workers_to_decrease] -= 1
            mgra_data[workers_to_increase] += 1
            mgra_data["decrease_min"] += workers_to_increase - workers_to_decrease

            # Check if we are done with this MGRA
            if mgra_data["decrease_min"] == 0:
                return mgra_data

    # Apply the MGRA adjustments for implied workers and 18+ population
    # Note we apply minimum implied workers first then household size categories
    # This is because the household size categories are a hard constraint whereas
    # the minimum implied workers is a soft constraint due to data limitations
    hh_workers = hh_workers.apply(adjust_mgra_18plus, axis=1).drop(
        columns=["tract", "persons_18plus", "min_implied_workers", "decrease_min"]
    )

    # For every MGRA, compute the difference between households by number of workers
    # and the households by size categories to determine necessary adjustments
    # Note that the household size categories are collapsed to 2+ and 3+
    hh_workers = hh_workers.merge(
        mgra_hhs, on=["run_id", "year", "mgra"], how="left"
    ).assign(
        diff2=lambda df: df["2"] - df[2],
        diff3=lambda df: df["3"] - df[3],
    )

    # The methodology to adjust each individual MGRA to not violate household size
    # constraints. Note that the household size categories are collapsed to 2+ and 3+
    # and that the 0 and 1 worker categories can always be added to as they imply
    # a minimum household size of 1+ which is satisfied by every category
    def adjust_mgra_hhs(mgra_data: pd.Series) -> pd.Series:
        if mgra_data["diff2"] >= 0 and mgra_data["diff3"] >= 0:
            return mgra_data
        while True:
            # Identify households by worker categories that need adjustment
            # As well as categories that can accommodate additional households
            workers_to_decrease = [
                category for category in [2, 3] if mgra_data[f"diff{category}"] < 0
            ]

            workers_to_increase = [
                category for category in [2, 3] if mgra_data[f"diff{category}"] > 0
            ]

            # Take the first worker category to decrease and select a worker category to increase
            # Use a weighted random methodology to select the category to increase
            # Note the 0 and 1 worker categories are always eligible to increase
            workers_to_decrease = workers_to_decrease[0]

            # If all categories to increase are 0 just choose one at a random
            if mgra_data[[0, 1] + workers_to_increase].sum() == 0:
                workers_to_increase = generator.choice([0] + workers_to_increase)
            else:
                workers_to_increase = generator.choice(
                    [0, 1] + workers_to_increase,
                    p=mgra_data[[0, 1] + workers_to_increase]
                    / mgra_data[[0, 1] + workers_to_increase].sum(),
                )

            # Execute the change and recompute the remaining change needed
            mgra_data[workers_to_decrease] -= 1
            mgra_data[f"diff{workers_to_decrease}"] += 1
            mgra_data[workers_to_increase] += 1
            mgra_data[f"diff{workers_to_increase}"] -= 1

            # Check if we are done with this MGRA
            if mgra_data["diff2"] >= 0 and mgra_data["diff3"] >= 0:
                return mgra_data

    # Apply the MGRA adjustments for household size categories
    hh_workers = hh_workers.apply(adjust_mgra_hhs, axis=1).drop(
        columns=["2", "3", "diff2", "diff3"]
    )

    return {
        "hh_workers": hh_workers.melt(
            id_vars=["run_id", "year", "mgra"],
            var_name="household_workers",
            value_name="hh",
        )
    }


def _validate_hh_income_outputs(hh_income_outputs: dict[str, pd.DataFrame]) -> None:
    """Validate the household income output data"""
    tests.validate_data(
        "MGRA Household Income",
        hh_income_outputs["hh_income"],
        row_count={"key_columns": {"mgra", "income_category"}},
        negative={},
        null={},
    )


def _validate_hh_size_outputs(hh_size_outputs: dict[str, pd.DataFrame]) -> None:
    """Validate the household size output data"""
    tests.validate_data(
        "MGRA Households by Size",
        hh_size_outputs["hh_size"],
        row_count={"key_columns": {"mgra", "household_size"}},
        negative={},
        null={},
    )


def _validate_hh_workers_outputs(hh_workers_outputs: dict[str, pd.DataFrame]) -> None:
    """Validate the household workers output data"""
    tests.validate_data(
        "MGRA Households by Workers",
        hh_workers_outputs["hh_workers"],
        row_count={"key_columns": {"mgra", "household_workers"}},
        negative={},
        null={},
    )


def _insert_hh_income(
    hh_income_inputs: dict[str, pd.DataFrame],
    hh_income_outputs: dict[str, pd.DataFrame],
    debug: bool,
) -> None:
    """Insert hh characteristics and tract level controls to database"""

    inputs_controls_tract = (
        hh_income_inputs["hh_income_tract_controls"][
            ["run_id", "year", "tract", "income_category", "value"]
        ]
        .rename(columns={"income_category": "metric"})
        .assign(metric=lambda df: "Income Category - " + df["metric"])
    )
    outputs_hh_characteristics = (
        hh_income_outputs["hh_income"][
            ["run_id", "year", "mgra", "income_category", "hh"]
        ]
        .rename(columns={"income_category": "metric", "hh": "value"})
        .assign(metric=lambda df: "Income Category - " + df["metric"])
    )

    # Save locally if in debug mode
    if debug:
        inputs_controls_tract.to_csv(
            utils.DEBUG_OUTPUT_FOLDER / "inputs_controls_tract_hh_income.csv",
            index=False,
        )
        outputs_hh_characteristics.to_csv(
            utils.DEBUG_OUTPUT_FOLDER / "outputs_hh_characteristics_hh_income.csv",
            index=False,
        )

    # Otherwise, load to database
    else:
        with utils.ESTIMATES_ENGINE.connect() as con:
            inputs_controls_tract.to_sql(
                schema="inputs",
                name="controls_tract",
                if_exists="append",
                con=con,
                index=False,
            )

            outputs_hh_characteristics.to_sql(
                schema="outputs",
                name="hh_characteristics",
                if_exists="append",
                con=con,
                index=False,
            )


def _insert_hh_size(
    hh_size_inputs: dict[str, pd.DataFrame],
    hh_size_outputs: dict[str, pd.DataFrame],
    debug: bool,
) -> None:
    """Insert hh characteristics and tract level controls to database"""

    inputs_controls_tract = (
        hh_size_inputs["hhs_tract_controls"]
        .rename(columns={"household_size": "metric"})
        .assign(
            metric=lambda df: "Household Size - "
            + df["metric"].astype(str).replace("7", "7+")
        )
    )
    outputs_hh_characteristics = (
        hh_size_outputs["hh_size"][["run_id", "year", "mgra", "household_size", "hh"]]
        .rename(columns={"household_size": "metric", "hh": "value"})
        .assign(
            metric=lambda df: "Household Size - "
            + df["metric"].astype(str).replace("7", "7+")
        )
    )

    # Save locally if in debug mode
    if debug:
        inputs_controls_tract.to_csv(
            utils.DEBUG_OUTPUT_FOLDER / "inputs_controls_tract_hh_size.csv", index=False
        )
        outputs_hh_characteristics.to_csv(
            utils.DEBUG_OUTPUT_FOLDER / "outputs_hh_characteristics_hh_size.csv",
            index=False,
        )

    # Otherwise, load to database
    else:
        with utils.ESTIMATES_ENGINE.connect() as con:
            inputs_controls_tract.to_sql(
                schema="inputs",
                name="controls_tract",
                if_exists="append",
                con=con,
                index=False,
            )

            outputs_hh_characteristics.to_sql(
                schema="outputs",
                name="hh_characteristics",
                if_exists="append",
                con=con,
                index=False,
            )


def _insert_hh_workers(
    hh_workers_inputs: dict[str, pd.DataFrame],
    hh_workers_outputs: dict[str, pd.DataFrame],
    debug: bool,
) -> None:
    """Insert hh characteristics and tract level controls to database"""

    inputs_controls_tract = (
        hh_workers_inputs["tract_workers"]
        .rename(columns={"household_workers": "metric"})
        .assign(
            metric=lambda df: "Household Workers - "
            + df["metric"].astype(str).replace("3", "3+")
        )
    )
    outputs_hh_characteristics = (
        hh_workers_outputs["hh_workers"][
            ["run_id", "year", "mgra", "household_workers", "hh"]
        ]
        .rename(columns={"household_workers": "metric", "hh": "value"})
        .assign(
            metric=lambda df: "Household Workers - "
            + df["metric"].astype(str).replace("3", "3+")
        )
    )

    # Save locally if in debug mode
    if debug:
        inputs_controls_tract.to_csv(
            utils.DEBUG_OUTPUT_FOLDER / "inputs_controls_tract_hh_workers.csv",
            index=False,
        )
        outputs_hh_characteristics.to_csv(
            utils.DEBUG_OUTPUT_FOLDER / "outputs_hh_characteristics_hh_workers.csv",
            index=False,
        )

    # Otherwise, load to database
    else:
        with utils.ESTIMATES_ENGINE.connect() as con:
            inputs_controls_tract.to_sql(
                schema="inputs",
                name="controls_tract",
                if_exists="append",
                con=con,
                index=False,
            )

            outputs_hh_characteristics.to_sql(
                schema="outputs",
                name="hh_characteristics",
                if_exists="append",
                con=con,
                index=False,
            )
