/*
Insert census tract controls for occupancy rate by structure type.
Census tracts without housing units default to using regional values.

Controls are generated by the 5-year ACS Detailed Tables
    B25024 - Units in Structure
    B25032 - Tenure by Units in Structure

Two input parameters are used
    run_id - the run identifier is used to get the list of census tracts
        in tandem with the year parameter that determines their vintage
    year - the year parameter is used to identify the 5-year ACS Detailed
        Tables release to use (ex. 2023 maps to 2019-2023) and the census
        tract geography vintage (2010-2019 uses 2010, 2020-2029 uses 2020)

Note, see https://github.com/SANDAG/Estimates-Program/issues/138 for
additional context on including the ACS category 'Boat, RV, van, etc.' in both
the 'Single Family - Detached' category and the 'Mobile Home' category
*/


SET NOCOUNT ON;
-- Initialize parameters -----------------------------------------------------
DECLARE @run_id integer = :run_id;
DECLARE @year integer = :year;


-- Send message if not all tables exist --------------------------------------
DECLARE @rows integer = (
    SELECT COUNT([table_id]) AS [rows]
    FROM [acs].[detailed].[tables]
    WHERE 
        [name] IN ('B25024', 'B25032')
        AND [year] = @year
        AND [product] = '5Y'
);

IF @rows = 0
    SELECT 'ACS 5-Year Table does not exist' AS [msg]
ELSE IF @rows != 2
    SELECT 'Incorrect number of ACS 5-Year Tables exist' AS [msg]
ELSE
BEGIN
    -- Build the expected return table Tract x Structure Type ----------------
    SELECT 
        [tract],
        [structure_type]
    INTO [#tt_shell]
    FROM (
        SELECT DISTINCT
            CASE WHEN @year BETWEEN 2010 AND 2019 THEN [2010_census_tract]
                WHEN @year BETWEEN 2020 AND 2029 THEN [2020_census_tract]
                ELSE NULL END AS [tract]
        FROM [inputs].[mgra]
        WHERE [run_id] = @run_id
    ) AS [tracts]
    CROSS JOIN (
        SELECT [structure_type] FROM (
            VALUES
                ('Single Family - Detached'),
                ('Single Family - Multiple Unit'),
                ('Multifamily'),
                ('Mobile Home')
        ) AS [tt] ([structure_type])
    ) AS [structure_type];


    -- Prepare intermediary results from ACS datasets ------------------------
    -- 5-year ACS Detailed Table B25024 - Units in Structure
    SELECT
        [tract],
        [structure_type],
        SUM([value]) AS [hs]
    INTO [#units]
    FROM (
        SELECT
            [tract],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!Boat, RV, van, etc.',
                    'Estimate!!Total:!!1, detached')
                    THEN [value]
                ELSE 0
            END AS [Single Family - Detached],
            CASE
                WHEN [label] = 'Estimate!!Total:!!1, attached' THEN [value]
                ELSE 0
            END AS [Single Family - Multiple Unit],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!2',
                    'Estimate!!Total:!!3 or 4',
                    'Estimate!!Total:!!5 to 9',
                    'Estimate!!Total:!!10 to 19',
                    'Estimate!!Total:!!20 to 49',
                    'Estimate!!Total:!!50 or more')
                    THEN [value]
                ELSE 0
            END AS [Multifamily],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!Boat, RV, van, etc.',
                    'Estimate!!Total:!!Mobile home')
                    THEN [value]
                ELSE 0
            END AS [Mobile Home]
        FROM [acs].[detailed].[values]
        LEFT JOIN [acs].[detailed].[geography]
            ON [values].[geography_id] = [geography].[geography_id]
        LEFT JOIN [acs].[detailed].[variables]
            ON [values].[variable] = [variables].[variable]
            AND [values].[table_id] = [variables].[table_id]
        LEFT JOIN [acs].[detailed].[tables]
            ON [values].[table_id] = [tables].[table_id]
        WHERE [tables].[name] = 'B25024'
            AND [tables].[year] = @year
            AND [tables].[product] = '5Y'
    ) AS [b25024]
    UNPIVOT (
        [value] FOR [structure_type] IN (
            [Single Family - Detached],
            [Single Family - Multiple Unit],
            [Multifamily],
            [Mobile Home]
        )
    ) AS [unpivot]
    GROUP BY [tract], [structure_type]
    HAVING SUM([value]) > 0

    -- 5-year ACS Detailed Table B25032 - Tenure by Units in Structure
    SELECT
        [tract],
        [structure_type],
        SUM([value]) AS [hh]
    INTO [#occupied]
    FROM (
        SELECT
            [tract],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!Owner-occupied housing units:!!Boat, RV, van, etc.',
                    'Estimate!!Total:!!Owner-occupied housing units:!!1, detached',
                    'Estimate!!Total:!!Renter-occupied housing units:!!Boat, RV, van, etc.',
                    'Estimate!!Total:!!Renter-occupied housing units:!!1, detached')
                    THEN [value]
                ELSE 0
            END AS [Single Family - Detached],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!Owner-occupied housing units:!!1, attached',
                    'Estimate!!Total:!!Renter-occupied housing units:!!1, attached')
                    THEN [value]
                ELSE 0
            END AS [Single Family - Multiple Unit],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!Owner-occupied housing units:!!2',
                    'Estimate!!Total:!!Renter-occupied housing units:!!2',
                    'Estimate!!Total:!!Owner-occupied housing units:!!3 or 4',
                    'Estimate!!Total:!!Renter-occupied housing units:!!3 or 4',
                    'Estimate!!Total:!!Owner-occupied housing units:!!5 to 9',
                    'Estimate!!Total:!!Renter-occupied housing units:!!5 to 9',
                    'Estimate!!Total:!!Owner-occupied housing units:!!10 to 19',
                    'Estimate!!Total:!!Renter-occupied housing units:!!10 to 19',
                    'Estimate!!Total:!!Owner-occupied housing units:!!20 to 49',
                    'Estimate!!Total:!!Renter-occupied housing units:!!20 to 49',
                    'Estimate!!Total:!!Owner-occupied housing units:!!50 or more',
                    'Estimate!!Total:!!Renter-occupied housing units:!!50 or more')
                    THEN [value]
                ELSE 0
            END AS [Multifamily],
            CASE
                WHEN [label] IN (
                    'Estimate!!Total:!!Owner-occupied housing units:!!Boat, RV, van, etc.',
                    'Estimate!!Total:!!Owner-occupied housing units:!!Mobile home',
                    'Estimate!!Total:!!Renter-occupied housing units:!!Boat, RV, van, etc.',
                    'Estimate!!Total:!!Renter-occupied housing units:!!Mobile home')
                    THEN [value]
                ELSE 0
            END AS [Mobile Home]
        FROM [acs].[detailed].[values]
        LEFT JOIN [acs].[detailed].[geography]
            ON [values].[geography_id] = [geography].[geography_id]
        LEFT JOIN [acs].[detailed].[variables]
            ON [values].[variable] = [variables].[variable]
            AND [values].[table_id] = [variables].[table_id]
        LEFT JOIN [acs].[detailed].[tables]
            ON [values].[table_id] = [tables].[table_id]
        WHERE [tables].[name] = 'B25032'
            AND [tables].[year] = @year
            AND [tables].[product] = '5Y'
    ) AS [b25032]
    UNPIVOT (
        [value] FOR [structure_type] IN (
            [Single Family - Detached],
            [Single Family - Multiple Unit],
            [Multifamily],
            [Mobile Home]
        )
    ) AS [unpivot]
    GROUP BY [tract], [structure_type];


    -- Create occupancy rates by structure type ------------------------------
    -- Calculate regional occupancy rates by structure type
    with [rate_region] AS (
        SELECT
            [#units].[structure_type],
            1.0 * SUM([hh]) / SUM([hs]) AS [occupancy_rate]
        FROM [#units]
        LEFT OUTER JOIN [#occupied]
            ON [#units].[tract] = [#occupied].[tract]
            AND [#units].[structure_type] = [#occupied].[structure_type]
        GROUP BY
            [#units].[structure_type]
    ),
    -- Calculate census tract occupancy rates by structure type
    [rate_tract] AS (
        SELECT
            [#units].[tract],
            [#units].[structure_type],
            1.0 * SUM([hh]) / SUM([hs]) AS [occupancy_rate]
        FROM [#units]
        LEFT OUTER JOIN [#occupied]
            ON [#units].[tract] = [#occupied].[tract]
            AND [#units].[structure_type] = [#occupied].[structure_type]
        GROUP BY
            [#units].[tract],
            [#units].[structure_type]
    )
    SELECT
        @run_id AS [run_id],
        @year AS [year],
        [#tt_shell].[tract],
        [#tt_shell].[structure_type],
        CASE WHEN [rate_tract].[occupancy_rate] IS NULL
                THEN [rate_region].[occupancy_rate]
            ELSE [rate_tract].[occupancy_rate]
        END AS [value]
    FROM [#tt_shell]
    LEFT OUTER JOIN [rate_region]
        ON [#tt_shell].[structure_type] = [rate_region].[structure_type]
    LEFT OUTER JOIN [rate_tract]
        ON [#tt_shell].[tract] = [rate_tract].[tract]
        AND [#tt_shell].[structure_type] = [rate_tract].[structure_type]


    -- Clean up --------------------------------------------------------------
    -- Drop the temporary tables
    DROP TABLE [#tt_shell]
    DROP TABLE [#units]
    DROP TABLE [#occupied]
END